name: CI

permissions:
  contents: write
  actions: write

on:
  workflow_run:
    workflows: ["Format"]
    types:
      - completed

concurrency:
  group: ${{ startsWith(github.event.pull_request.title, 'flake:') && 'flake-prs' || format('pr-{0}', github.event.pull_request.number) }}
  cancel-in-progress: ${{ startsWith(github.event.pull_request.title, 'flake:') }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    if: ${{ github.event_name == 'pull_request' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            system: nixos
          - os: macos-latest
            system: darwin
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
      - uses: nixbuild/nix-quick-install-action@v32
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - uses: cachix/cachix-action@v16
        with:
          name: potb
          authToken: ${{ secrets.CACHIX_TOKEN }}
          pushFilter: '(WebStorm|webstorm|-source(?:-|$))'
      - name: Build NixOS configuration
        if: matrix.system == 'nixos'
        run: nix build .#nixosConfigurations.charon.config.system.build.toplevel
      - name: Build Darwin configuration
        if: matrix.system == 'darwin'
        run: nix build .#darwinConfigurations.nyx.system

