name: CI

permissions:
  contents: write
  actions: write

on:
  pull_request:

concurrency:
  group: ${{ startsWith(github.event.pull_request.title, 'flake:') && 'flake-prs' || format('pr-{0}', github.event.pull_request.number) }}
  cancel-in-progress: ${{ startsWith(github.event.pull_request.title, 'flake:') }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            system: nixos
          - os: macos-latest
            system: darwin
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
      - uses: nixbuild/nix-quick-install-action@v32
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - uses: cachix/cachix-action@v16
        with:
          name: potb
          authToken: ${{ secrets.CACHIX_TOKEN }}
          pushFilter: '(WebStorm|webstorm|-source(?:-|$))'
      - name: Build NixOS configuration
        if: matrix.system == 'nixos'
        run: nix build .#nixosConfigurations.charon.config.system.build.toplevel
      - name: Build Darwin configuration
        if: matrix.system == 'darwin'
        run: nix build .#darwinConfigurations.nyx.system
      - name: Build home-manager configuration (NixOS)
        if: matrix.system == 'nixos'
        run: nix build .#homeConfigurations."potb@charon".activationPackage
      - run: nix fmt .
      - run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -am "Apply nix fmt"
            git push origin HEAD:${{ github.head_ref }}
          fi

