name: CI

permissions:
  contents: write
  actions: write

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
      - uses: nixbuild/nix-quick-install-action@v32
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - uses: cachix/cachix-action@v16
        with:
          name: potb
          authToken: ${{ secrets.CACHIX_TOKEN }}
          pushFilter: '(WebStorm|webstorm)'
      - run: nix build .#nixosConfigurations.charon.config.system.build.toplevel
      - run: nix build .#homeConfigurations."potb@charon".activationPackage
      - run: nix fmt .
      - run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -am "Apply nix fmt"
            git push origin HEAD:${{ github.head_ref }}
          fi

