name: Format

permissions:
  contents: write

on:
  pull_request:

concurrency:
  group: ${{ format('format-pr-{0}', github.event.pull_request.number) }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
      - uses: nixbuild/nix-quick-install-action@v32
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - run: nix fmt .
      - run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -am "Apply nix fmt"
            git push origin HEAD:${{ github.head_ref }}
          fi